# Generated by Django 2.2.19 on 2021-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CW_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chw_username', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('session', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('player_class', models.CharField(max_length=10)),
                ('send_report', models.CharField(max_length=32)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-registration_date'],
            },
        ),
    ]
