# Generated by Django 3.2.6 on 2021-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cw_players',
            options={'ordering': ['-registration_date'], 'verbose_name': 'игрока', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='cw_players',
            name='send_report',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cw_players',
            name='session',
            field=models.CharField(max_length=355),
        ),
    ]
