# Generated by Django 3.2.9 on 2021-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211020_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw_players',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
