# Generated by Django 3.2.9 on 2022-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cw_players_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw_players',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cw_players',
            name='player_class',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cw_players',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
