# Generated by Django 3.2.9 on 2022-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cw_players_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw_players',
            name='defcow',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
