# Generated by Django 3.2.9 on 2022-04-16 22:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cw_players_defcow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw_players',
            name='send_report',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), blank=True, null=True, size=None),
        ),
    ]
